image: gcc:6.1

pipelines:
  default:
    - step:
        name: Build and test
        script:
          - git clone https://bitbucket.org/malb/m4ri
          - cd m4ri
          - autoreconf -i
          - ./configure
          - make
          - make install
          - cd ..
          - autoreconf -i
          - ./configure
          - make
          - make distcheck